# Generated by Django 3.2.5 on 2021-07-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
                ('image', models.CharField(default=None, max_length=300)),
                ('year', models.PositiveBigIntegerField(default=None)),
                ('designer', models.CharField(default=None, max_length=50)),
                ('color', models.CharField(default=None, max_length=50)),
                ('description', models.CharField(default=None, max_length=100)),
            ],
        ),
    ]
