# Generated by Django 3.2.5 on 2021-07-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('type', '0001_initial'),
        ('furniture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='type',
            field=models.ManyToManyField(related_name='furniture', to='type.Type'),
        ),
    ]
