# Generated by Django 3.2.5 on 2021-07-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_rename_rooms_room'),
        ('furniture', '0002_show_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='room',
            field=models.ManyToManyField(related_name='furniture', to='rooms.Room'),
        ),
    ]
